module.exports = [{
  fileNameBase: 'agency',
  collection: 'agencies'
}, {
  fileNameBase: 'calendar_dates',
  collection: 'calendardates'
}, {
  fileNameBase: 'calendar',
  collection: 'calendars'
}, {
  fileNameBase: 'fare_attributes',
  collection: 'fareattributes'
}, {
  fileNameBase: 'fare_rules',
  collection: 'farerules'
}, {
  fileNameBase: 'feed_info',
  collection: 'feedinfos'
}, {
  fileNameBase: 'frequencies',
  collection: 'frequencies'
}, {
  fileNameBase: 'routes',
  collection: 'routes'
}, {
  fileNameBase: 'shapes',
  collection: 'shapes'
}, {
  fileNameBase: 'stop_times',
  collection: 'stoptimes'
}, {
  fileNameBase: 'stops',
  collection: 'stops'
}, {
  fileNameBase: 'transfers',
  collection: 'transfers'
}, {
  fileNameBase: 'trips',
  collection: 'trips'
}, {
  fileNameBase: 'timetables',
  collection: 'timetables',
  nonstandard: true
}, {
  fileNameBase: 'timetable_stop_order',
  collection: 'timetablestoporders',
  nonstandard: true
}];
